#! /bin/bash

### Default setting ###
flag_np=false 
flag_dir=false
flag_inp=false
opterr=false
nprocs=1

# Directory (please change accordingly)
QDIR=/home/${USER}/test/quket   #  directory where main.py exists
WDIR=/work/${USER}/data    #  working directory
if [ ! -d $WDIR ]; then
  mkdir $WDIR
fi  
python=`which python3.8`
#python=/usr/local/bin/python3.8
# For Ravel
MPI_tcp='-genv I_MPI_FABRICS tcp' 
# For Titan
MPI_tcp='' 

### Check options
while [ $# -gt 0 ]
do
  case $1 in
    -np)    flag_np=true;  nprocs="$2";;
    -np=*)  flag_np=true;  nprocs="${1#-np=}";;
    -dir)   flag_dir=true; QDIR="$2";;
    -dir=*) flag_dir=true; QDIR="${1#-dir=}";;
    -*) opterr=true; echo "Unknown option: $1";;
    *)  flag_inp=true; input="$1";;
  esac
  shift
done

if [ ! -e ${input}.inp ]; then
    echo "No input file '${input}.inp' exits!" 
    exit
fi

nohup mpirun -np $nprocs $MPI_tcp $python -m mpi4py ${QDIR}/main.py $input > ${input}.out  && exit 

