#! /bin/bash
flag_np=false 
flag_dir=false
flag_inp=false
opterr=false
nprocs=1
#QDIR=/home/tsuchimochi/quket
QDIR=`pwd`

while [ $# -gt 0 ]
do
  case $1 in
    -np)    flag_np=true;  nprocs="$2";;
    -np=*)  flag_np=true;  nprocs="${1#-np=}";;
    -dir)   flag_dir=true; QDIR="$2";;
    -dir=*) flag_dir=true; QDIR="${1#-dir=}";;
    -*) opterr=true; echo "Unknown option: $1";;
    *)  flag_inp=true; input="$1";;
  esac
  shift
done

nohup mpirun -np $nprocs -genv I_MPI_FABRICS tcp python3.8 ${QDIR}/main.py $input > ${input}.out  && exit 
